# Generated by Django 3.2.8 on 2022-12-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户编号')),
                ('status', models.IntegerField(choices=[(1, '可使用'), (0, '已注销')], verbose_name='用户状态')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户姓名')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='用户电话')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='地址编号')),
                ('location', models.TextField(blank=True, null=True, verbose_name='地址信息')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='消费者编号')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
