# Generated by Django 3.2.8 on 2022-12-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='地址编号'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, '已登录'), (0, '未登录')], verbose_name='用户状态'),
        ),
    ]
