# Generated by Django 3.2.8 on 2022-12-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wicket', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='菜品价格')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='菜品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='菜品描述')),
                ('wic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wicket.wicket', verbose_name='菜品窗口号')),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('status', models.IntegerField(choices=[(0, '已下单'), (1, '已发货'), (2, '已收货'), (3, '已取消')], default=0, verbose_name='订单状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='总价')),
                ('creat_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('contact_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='联系方式')),
                ('count', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='菜品数量')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='订单用户编号')),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dish.dish', verbose_name='菜品编号')),
            ],
            options={
                'db_table': 'customer_order',
            },
        ),
    ]
