# Generated by Django 3.2.8 on 2022-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='餐厅编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='餐厅名称')),
                ('location', models.TextField(blank=True, null=True, verbose_name='餐厅位置')),
                ('number_of_wicket', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='餐厅窗口数')),
                ('status', models.IntegerField(choices=[(1, '营业中'), (0, '休息中')], verbose_name='餐厅状态')),
            ],
            options={
                'db_table': 'canteen',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='管理员编号')),
                ('status', models.IntegerField(choices=[(1, '可使用'), (0, '已注销')], verbose_name='管理员状态')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='管理员姓名')),
                ('manage', models.ManyToManyField(to='canteen.Canteen')),
            ],
            options={
                'db_table': 'administrator',
            },
        ),
    ]
