# Generated by Django 3.2.8 on 2022-12-24 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canteen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wicket',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='窗口编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='窗口名称')),
                ('status', models.IntegerField(choices=[(0, '营业中'), (1, '未营业')], verbose_name='窗口状态')),
                ('can_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen.canteen', verbose_name='餐厅编号')),
            ],
            options={
                'db_table': 'wicket',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='商户编号')),
                ('status', models.IntegerField(choices=[(1, '可使用'), (0, '已注销')], verbose_name='商户状态')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='商户密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='商户昵称')),
                ('management', models.ManyToManyField(to='wicket.Wicket')),
            ],
            options={
                'db_table': 'merchant',
            },
        ),
    ]
