# Generated by Django 3.2.8 on 2022-12-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wicket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='窗口编号'),
        ),
    ]
