# Generated by Django 3.2.8 on 2022-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wicket', '0002_alter_wicket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='management',
            new_name='wickets',
        ),
        migrations.AlterField(
            model_name='wicket',
            name='status',
            field=models.IntegerField(choices=[(1, '营业中'), (0, '未营业')], verbose_name='窗口状态'),
        ),
    ]
